### PR TITLE
Blade 643

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
@yanan, Let's make sure we fix the tests before we merge to upstream.

**Comment by yanan** [comment]
Sure, I've run into an error on non-windows, but I can't reproduce it when run it locally on my machine, I'm not sure about it. Have you error run into this error before?

```
* What went wrong:
Execution failed for task ':cli:testBladeCreateCommandJsTheme'.
> assert !error.contains("error")
         ||     |
         ||     true
         |'   create .gitignore\n   create gulpfile.js\n   create package.json\n   create src/web-inf/liferay-look-and-feel.xml\n   create src/web-inf/liferay-plugin-package.properties\n   create src/images/thumbnail.png\n   create src/css/_custom.scss\nevents.js:182\n      throw er; // unhandled \'error\' event\n      ^\n\nsyntaxerror: invalid regular expression: /(?<=translatex?(?!y)\\()\\s*(?=,|\\))/: invalid group\n    at object.<anonymous> (/home/runner/.blade/cache/yo-10.x/node_modules/liferay-theme-tasks/lib/r2/liferay-r2/index.js:85:25)\n    at module._compile (module.js:573:30)\n    at object.module._extensions..js (module.js:584:10)\n    at module.load (module.js:507:32)\n    at trymoduleload (module.js:470:12)\n    at function.module._load (module.js:462:3)\n    at module.require (module.js:517:17)\n    at require (internal/module.js:11:18)\n    at object.<anonymous> (/home/runner/.blade/cache/yo-10.x/node_modules/liferay-theme-tasks/theme/index.js:12:12)\n    at module._compile (module.js:573:30)\n'
```

**Comment by lawrence-lee** [comment]
This test isn't being run on windows, so that's why its green there. 

Here's the test, https://github.com/liferay/liferay-blade-cli/blob/master/cli/blade-jar-smoke-tests.gradle#L55.

**Comment by lawrence-lee** [comment]
This could be a node version change because you changed it with project templates and workspace

**Comment by lawrence-lee** [comment]
If you can't figure this out by end of day, can we revert these changes so we can publish snapshots again?

**Comment by yanan** [comment]
I've tried remove cache in .blade/cache/yo-10.x/node_modules/liferay-theme-tasks/lib/r2/liferay-r2 and it successfully once .blade/cache/yo-10.x/node_modules/liferay-theme-tasks/lib/r2/liferay-r2, but it's not stable, I will check and if not working will revert later today

**Comment by yanan** [comment]
Once revert project.template, the problem still exists: https://github.com/liferay/liferay-blade-cli/pull/166

**Comment by yanan** [comment]
Hi @lawrence-lee , I find the node version in NodeUtil.java is 8.4.0, once switching to latest 14.17.6, it works. Is that ok to use the latest node version?
I've resend the pr here https://github.com/liferay/liferay-blade-cli/pull/167

**Pull request closed without merging**
